version: '3.8'

services:
  db:
    build:
      context: ../flaskimmobilier/database
      dockerfile: Dockerfile
    volumes:
      - ../flaskimmobilier/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: immobilier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: groupe7
    ports:
      - "5432:5432"  # Port mapping pour accéder à PostgreSQL depuis l'hôte

  imobilierapp:
    build:
      context: ../flaskimmobilier/imobilierapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db  # Dépendance du service imobilierapp sur le service db
    links:
      - db  # Lier le service imobilierapp au service db

  nginx:
    build:
      context: ../flaskimmobilier/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - imobilierapp  # Dépendance du service nginx sur le service imobilierapp
